### ISSUE TITLE
`vspec.py` does not import `sys`

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vss-tools#10]
## Reproduction
```bash
$ git clone git@github.com:GENIVI/vehicle_signal_specification.git
$ pip install vehicle_signal_specification @ git+ssh://git@github.com/GENIVI/vehicle_signal_specification.git#egg=vehicle_signal_specification&subdirectory=vss-tools
$ python3
>>> from vspec import load
>>> vspec.load('VehicleSignalSpecification.vspec', ['./conf/vss/spec'])
```

## Expected
Specification loads, or at least loads with a correct error message

## Actual
```pytb
Traceback (most recent call last):
  File "/Users/rrowe/Library/Application Support/JetBrains/PyCharm2020.1/scratches/scratch_5.py", line 3, in <module>
    vspec.load('VehicleSignalSpecification.vspec', ['./conf/vss/spec'])
  File "/Users/rrowe/.local/share/virtualenvs/wormtongue-worker-_Xbg4RH4/lib/python3.8/site-packages/vspec.py", line 209, in load
    absolute_path_flat_model_with_id = assign_signal_uuids(absolute_path_flat_model)
  File "/Users/rrowe/.local/share/virtualenvs/wormtongue-worker-_Xbg4RH4/lib/python3.8/site-packages/vspec.py", line 200, in assign_signal_uuids
    elem["uuid"] = db_mgr.get_or_assign_signal_uuid(elem["$name$"])
  File "/Users/rrowe/.local/share/virtualenvs/wormtongue-worker-_Xbg4RH4/lib/python3.8/site-packages/vspec.py", line 121, in get_or_assign_signal_uuid
    sys.exit(255)
NameError: name 'sys' is not defined
```

## Solution
Add to `vspec.py`:
```python
import sys
```

**Comment by rfrowe** [comment]
Closing, as this is actually an issue on [GENIVI/vehicle_signal_specification](https://github.com/GENIVI/vehicle_signal_specification)

**Comment by gunnarx** [comment]
Reopened.
@rfrowe You were correct the first time.  Changes to the code should be reported and fixed in this repository.  Thanks for your input.

**Comment by gunnarx** [comment]
... but that also means that I'm not sure how to achieve what you want to do with the pip install.

The process we generally use is to clone (recursively since vehicle_signal_specification includes vss-tools as a git submodule) and then run from there:

$ git clone --recursive https://github.com/GENIVI/vehicle_signal_specification.git
$ cd vehicle_signal_specification
$ make

and that "just works" here. Nothing more should be required.

Q: What is it you want to achieve by using pip install?

However, you are right about your observation for the _currently used_ version of vss-tools.
The git submodule points to a particular version, and it ought to be updated now, because actually the latest code already has
**import sys** in the code:  https://github.com/GENIVI/vss-tools/blob/master/vspec.py#L15

**Comment by rfrowe** [comment]
What I hope to achieve by using pip install is to install vspec so that I can use an existing python tool to load the VSS rather than write my own parser. In the end, I used make to generate a JSON form of the spec and wrote a parser for that.

As per [your comment](https://github.com/GENIVI/vehicle_signal_specification/issues/175#issuecomment-672824170) on GENIVI/vehicle_signal_specification#175, you can probably close this.

**Comment by gunnarx** [comment]
Yes, what @rfrowe said.  The submodules are also not set up to explicitly track a branch currently, although this will cause the default origin/master to be used.

> If you checkout and run make you will get VSS Main #1 and VSS Tools #1 (not latest and greatest).
> I'd propose that we'd rather try to run on master for each submodule. Otherwise, we'll have to update the main repository every time we have one of the submodules updated (or accept that the state of the submodules might be stale).

In many projects I think it is preferrable to not track a branch but to manually move the submodules to a new revision, because it ensures the build is fully defined and repeatable.  Yes it takes a bit of work but it is also repeatable.  

>  (or accept that the state of the submodules might be stale).

We shouldn't be making too many not backwards compaible changes so I'm thinking this is possibly not a major issue during development.  Let's get some more opinions in to see what is preferred.

In general things should get better when https://github.com/GENIVI/vss-tools/issues/12 is done.
The current way it is proposed, vehicle_signal_specification will do automated builds on any change in that repository, i.e. the "latest" vehicle_signal_specification, and the *current** submodule revision, while **vss-tools** will build with the tip of the master branch (or the PR that is being checked) combined with **vehicle_signal_specification** master.  Thus we should be alerted if anything is incompatible before it makes it into **vehicle_signal_specification** and before it gets into the submodule **vss-tools**?

>  `git submodule foreach git pull origin master` instead of the regular submodule update.

yes or `update --remote` as previously said.

**Comment by danielwilms** [comment]
depends on #19

**Comment by gunnarx** [comment]
#19 is now closed.  I'm not sure if there's anything left to do on this?

**Comment by gunnarx** [comment]
For what it's worth the original statement seems fixed.

`vspec.py` **does** include `sys` now:

https://github.com/GENIVI/vss-tools/blob/b287be70811de5076e4be17de2a193e6743083be/vspec.py#L15

**Comment by rfrowe** [comment]
Whoa that's pretty cool, didn't know you can reference lines like that. I'm fine closing this

**Comment by SebastianSchildt** [comment]
This should be closed. Lacking the power... @gunnarx
