### ISSUE TITLE
Gonative tool

### ISSUE THREAD

**Issue by UlfBj** [GENIVI/vss-tools#27]
A number of implementations used in the CCS demo project that require access to the VSS tree are implemented in Go ( https://github.com/MEAE-GOT/W3C_VehicleSignalInterfaceImpl/, https://github.com/GENIVI/ccs-w3c-client). They currently use the cnative format, which require the cgo package, and leads to a somewhat complicated build chain. This could be avoided with a tool that generates a gonative format, together with a Go parser libary. 
I therefore propose that such a tool is added to the tool suite, and I volunteer to implement it if there is backing for it.

**Comment by gunnarx** [comment]
Are there no YAML parsers available for Go that could be used directly?

**Comment by UlfBj** [comment]
There are "YAML support" packages in Go, that is not the problem. The problem would be to implement the parser services that a "tree server" would need, e.g. the ability to search the tree for a given path, that may include wildcards. Even if we assume we have a tool that combines the collection of YAML files that represent the tree into one file, and expands the instances, this would not in my view be an efficient solution. Anyone is free to prove me wrong on that;).

**Comment by gunnarx** [comment]
> The problem would be to implement the parser services that a "tree server" would need, e.g. the ability to search the tree for a given path, that may include wildcards.

This sounds like some convenience functions (services it needs) and that is "not the problem" as I see it :)  (Or put it another way, I think it is a separate issue)

> Even if we assume we have a tool that combines the collection of YAML files that represent the tree into one file

It is my general preference, that we use the original YAML files as the official definition and that all programs try to consume that format per default.  But if we want to change that and use another format as an official input to tools, then let's discuss that.  I would still recommend that to be a single format rather than creating different ones for every environment.

> and expands the instances, this would not in my view be an efficient solution. Anyone is free to prove me wrong on that;).

Please clarify, "efficient" from which perspective?  Is it about run-time efficiency, or programming effort?

Overall I have to guess what the core of this is, and it sounds like some convenience code that is written _once_ and that all Go-programs can make use of without having to repeat that code?   Is that right?  I would call it a convenience library, or it is sometimes called a "client library".  That in itself doesn't seem to need a separate file format as far as I can tell - it just needs a common single implementation.  Or?

**Comment by UlfBj** [comment]
>> It is my general preference, that we use the original YAML files as the official definition and that all programs try to consume that format per default. 

The YAML files are the official definition. They are just translated to another format, but logically identical to the YAML files,

>> But if we want to change that and use another format as an official input to programs, then let's discuss that. I would still recommend that to be a single format rather than creating different ones for every environment.

The cnative/gonative format could be merged into a common format that is language independent. They are already now language independent, the c/go prefix rather refers to the associated parser. 

>> Please clarify, "efficient" from which perspective? Is it about run-time efficiency, or programming effort?

It is about run-time efficiency. My view comes from what I have heard from an implementation that used a JSON-formatted tree.

>>Overall I have to guess what the core of this is, and it sounds like some convenience code that is written once and that all Go-programs can make use of without having to repeat that code? Is that right? I would call it a convenience library, or it is sometimes called a "client library". That in itself doesn't seem to need a separate file format as far as I can tell - it just needs a common single implementation. Or?

It can be called a convenience library for all Go programs.
The file format is not language dependent, so it could be shared with e. g. the C language library.

**Comment by gunnarx** [comment]
> It is about run-time efficiency. My view comes from what I have heard from an implementation that used a JSON-formatted tree.

OK, I see.   My view is that programs usually read data into memory and organize it in whatever data structures they need to then have good run-time efficiency once the real processing starts.  This only happens once at startup so it is rarely a performance concern.  That "optimized" data structure lives in memory in the program, so it is putting that data structure in a file on disk first that I find a little bit uncommon.

**Comment by gunnarx** [comment]
The corresponding PR #28 has been merged -> Closing issue.
