### ISSUE TITLE
Package is not installable without parent repo

### ISSUE THREAD

**Issue by rfrowe** [GENIVI/vss-tools#9]
## Description
`setup.py` requires `../VERSION` during installation, which means that it's impossible to install this Python package without cloning it as a submodule of [GENIVI/vehicle_signal_specification](https://github.com/GENIVI/vehicle_signal_specification)

## Expected
Installation of package should succeed with just the contents of this repo

## Actual
```pytb
FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
```

## Solution
One or more of:
1. this repo should not be a submodule
1. `setup.py` should be moved to the parent repo
1. this package should be published to PyPi

**Comment by gunnarx** [comment]
> Installation of package should succeed with just the contents of this repo

Yes, this sounds reasonable.  I wasn't originally sure if this repo need to be "installable" since it is safe to assume that vehicle_signal_specification is needed in combination, but if we are going to support it, I agree it should be possible without the parent repo.

> 1. this repo should not be a submodule
> 2. setup.py should be moved to the parent repo
> 3. this package should be published to PyPi

Hmm,  I'm not sure I like any of those options...   We recently moved it to a submodule for a reason, would like to avoid reversing that decision.    (Of course nothing against publishing on PyPi, but I don't think it should be necessary).

Why are we dependent on the VERSION file again?  Shouldn't the vss-tools version be independent from the VSS version since we decided on different repos?

**Comment by danielwilms** [comment]
> We recently moved it to a submodule for a reason, would like to avoid reversing that decision.

But we introduced quite a bit of complexity with it.

> Why are we dependent on the VERSION file again? Shouldn't the vss-tools version be independent from the VSS version since we decided on different repos?

Yes, it should be independent. The specification relies on it for the naming of the resulting files, which is done in the `Makefile` in the repository of the specification. Tools should have a separate version.

**Comment by Floix** [comment]
The VERSION file is used in vss-tools to notify about deprecations. We could get rid of it, by introducing our own version management in vss-tools

**Comment by gunnarx** [comment]
Is the linked PR above an OK solution?

**Comment by rfrowe** [comment]
Sorry, yes that's satisfactory. Thanks!
